services:
  postgres:
    image: postgres:16-alpine
    container_name: njored-backend-postgres-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: njored
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "5432:5432"
    volumes:
      - njored_pg_data:/var/lib/postgresql/data
    networks:
      - njored_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d njored"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  ktor-app:
    image: edmound776/njored-backend:latest
    container_name: njored-backend-ktor-app-1
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=njored
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy                 # Waits until DB is ready
    networks:
      - njored_default

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: njored-backend-cloudflare-tunnel-1
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - njored_default

networks:
  njored_default:
    driver: bridge

volumes:
  njored_pg_data:
